version: '3.7'

services:
  psql:
    image: postgres
    container_name: 'psql-lg'
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./migrations/test_insert.sql:/docker-entrypoint-initdb.d/test_insert.sql:ro
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  app:
    container_name: 'lg'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    depends_on:
      - psql
